// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/da919fe791a4deb9eea45684a8daf035f9aafe8a/qrcode-generator/qrcode-generator.d.ts
interface QRCode {
    addData(data: string) : void;
    make() : void;
    
    createTableTag(cellSize: number, margin: number) : string;
    createSvgTag(cellSize: number, margin: number) : string;
    createImageTag(cellSize: number, margin: number) : string;    
}

declare module 'qrcode-generator' {
    function qrcode(type: number, errorCorrectionLevel: string) : QRCode;
    export = qrcode;
}