// Generated by typings
// Source: https://raw.githubusercontent.com/stefanhuber/DefinitelyTyped/3ea8a6280f82118bd942cae312bc857ebeb56c1b/bip21/bip21.d.ts
declare module bip21 {
    export function decode(uri:string) : {address:string,amount?:number}; 
    export function encode(address:string,options?:any) : string;
}

declare module "bip21" {
    export = bip21;
}